--------------------------------------------------------------------------------
-- 01_dimensiones.sql
-- DWH OEFA · Oracle BD_CURSOR
-- Creación de las 6 tablas de dimensiones del modelo (ver PROPUESTA_ADAPTADA_ETL.md, sec. 3.2)
--
-- Orden de ejecución: EJECUTAR PRIMERO (los hechos referencian a estas tablas por FK).
-- Motor objetivo: Oracle 12c+ (usa GENERATED BY DEFAULT ON NULL AS IDENTITY, disponible
-- desde 12c). Si el BD_CURSOR corre en una versión anterior, reemplazar la identidad por
-- una SEQUENCE + TRIGGER equivalente.
--
-- Convención: cada dimensión trae sembrado un miembro "NO ESPECIFICADO" con clave -1,
-- para que ningún hecho se pierda por falta de dimensión (ver sección 3.2 de la propuesta).
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- DIM_TIEMPO
-- Clave inteligente AAAAMMDD. Se puebla con un script de generación de calendario
-- (fuera del alcance de este DDL); aquí solo se crea la estructura y el miembro ND.
--------------------------------------------------------------------------------
CREATE TABLE DIM_TIEMPO (
    ID_TIEMPO             NUMBER(8)      NOT NULL,   -- AAAAMMDD; -1 = NO ESPECIFICADO
    FECHA                 DATE,
    ANIO                  NUMBER(4),
    MES                   NUMBER(2),
    NOMBRE_MES             VARCHAR2(15),
    TRIMESTRE             NUMBER(1),
    SEMANA_ANIO           NUMBER(2),
    DIA                   NUMBER(2),
    DIA_SEMANA            VARCHAR2(10),
    NOMBRE_DIA            VARCHAR2(15),
    ES_FIN_DE_SEMANA      NUMBER(1)      DEFAULT 0,
    ES_FERIADO            NUMBER(1)      DEFAULT 0,
    ES_DIA_HABIL          NUMBER(1)      DEFAULT 1,
    DESCRIPCION_FERIADO   VARCHAR2(200),
    CONSTRAINT PK_DIM_TIEMPO PRIMARY KEY (ID_TIEMPO),
    CONSTRAINT CK_DIM_TIEMPO_FDS CHECK (ES_FIN_DE_SEMANA IN (0,1)),
    CONSTRAINT CK_DIM_TIEMPO_FER CHECK (ES_FERIADO IN (0,1)),
    CONSTRAINT CK_DIM_TIEMPO_HAB CHECK (ES_DIA_HABIL IN (0,1))
);

CREATE UNIQUE INDEX UQ_DIM_TIEMPO_FECHA ON DIM_TIEMPO (FECHA);

-- Miembro NO ESPECIFICADO
INSERT INTO DIM_TIEMPO (ID_TIEMPO, FECHA, ANIO, MES, NOMBRE_MES, TRIMESTRE,
                         SEMANA_ANIO, DIA, DIA_SEMANA, NOMBRE_DIA,
                         ES_FIN_DE_SEMANA, ES_FERIADO, ES_DIA_HABIL, DESCRIPCION_FERIADO)
VALUES (-1, NULL, NULL, NULL, 'NO ESPECIFICADO', NULL,
        NULL, NULL, 'NO ESPECIFICADO', 'NO ESPECIFICADO',
        0, 0, 0, NULL);

--------------------------------------------------------------------------------
-- DIM_ADMINISTRADO
-- Sin SCD Tipo 2: última versión vigente, actualizada por UPDATE simple.
--------------------------------------------------------------------------------
CREATE TABLE DIM_ADMINISTRADO (
    ID_ADMINISTRADO       NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    COD_ADMINISTRADO      VARCHAR2(50)   NOT NULL,   -- ADM##### (SISUD) o NOM-<razón social>
    RAZON_SOCIAL          VARCHAR2(300),
    RAZON_SOCIAL_NORM     VARCHAR2(300),
    RUC                   VARCHAR2(20),
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DIM_ADMINISTRADO PRIMARY KEY (ID_ADMINISTRADO),
    CONSTRAINT UQ_DIM_ADMINISTRADO_COD UNIQUE (COD_ADMINISTRADO)
);

INSERT INTO DIM_ADMINISTRADO (ID_ADMINISTRADO, COD_ADMINISTRADO, RAZON_SOCIAL,
                               RAZON_SOCIAL_NORM, RUC)
VALUES (-1, 'ND', 'NO ESPECIFICADO', 'NO ESPECIFICADO', NULL);

--------------------------------------------------------------------------------
-- DIM_ORGANO_UNIDAD
-- Oficinas/coordinaciones/direcciones (ej. DSIS-CRES, DSEM-CMIN, ODES-MOQ, OD-LAM).
--------------------------------------------------------------------------------
CREATE TABLE DIM_ORGANO_UNIDAD (
    ID_ORGANO             NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    SIGLA                 VARCHAR2(30)   NOT NULL,
    NOMBRE                VARCHAR2(200),
    TIPO                  VARCHAR2(30),   -- DIRECCION / COORDINACION / ODES / OD
    ORGANO_SUPERIOR       VARCHAR2(30),
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DIM_ORGANO_UNIDAD PRIMARY KEY (ID_ORGANO),
    CONSTRAINT UQ_DIM_ORGANO_SIGLA UNIQUE (SIGLA),
    CONSTRAINT CK_DIM_ORGANO_TIPO CHECK (TIPO IN
        ('DIRECCION','COORDINACION','ODES','OD','NO ESPECIFICADO'))
);

INSERT INTO DIM_ORGANO_UNIDAD (ID_ORGANO, SIGLA, NOMBRE, TIPO, ORGANO_SUPERIOR)
VALUES (-1, 'ND', 'NO ESPECIFICADO', 'NO ESPECIFICADO', NULL);

--------------------------------------------------------------------------------
-- DIM_MATERIA_SUBSECTOR
--------------------------------------------------------------------------------
CREATE TABLE DIM_MATERIA_SUBSECTOR (
    ID_MATERIA            NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    NOMBRE                VARCHAR2(100)  NOT NULL,
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DIM_MATERIA PRIMARY KEY (ID_MATERIA),
    CONSTRAINT UQ_DIM_MATERIA_NOMBRE UNIQUE (NOMBRE)
);

INSERT INTO DIM_MATERIA_SUBSECTOR (ID_MATERIA, NOMBRE) VALUES (-1, 'NO ESPECIFICADO');
INSERT INTO DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('HIDROCARBUROS');
INSERT INTO DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('PESQUERIA');
INSERT INTO DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('MINERIA');
INSERT INTO DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('RESIDUOS SOLIDOS');
INSERT INTO DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('INDUSTRIAS');
INSERT INTO DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('AGUAS');

--------------------------------------------------------------------------------
-- DIM_ESTADO
-- Catálogo homologado de estados (resuelve el hallazgo H8: estados como texto libre
-- sin catálogo único). TIPO_ESTADO agrupa por dominio (RESOLUCION/MULTA/PAGO/ETAPA/
-- DESCARGOS/INFORME); GRUPO clasifica el estado homologado.
--------------------------------------------------------------------------------
CREATE TABLE DIM_ESTADO (
    ID_ESTADO             NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    TIPO_ESTADO           VARCHAR2(30)   NOT NULL,   -- RESOLUCION/MULTA/PAGO/ETAPA/DESCARGOS/INFORME
    CODIGO                VARCHAR2(50)   NOT NULL,   -- valor homologado (ej. ACTIVO, PAGADO)
    DESCRIPCION           VARCHAR2(200),
    GRUPO                 VARCHAR2(30),   -- VIGENTE/CERRADO/CUMPLIDO/INCUMPLIDO/PENDIENTE
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DIM_ESTADO PRIMARY KEY (ID_ESTADO),
    CONSTRAINT UQ_DIM_ESTADO UNIQUE (TIPO_ESTADO, CODIGO)
);

INSERT INTO DIM_ESTADO (ID_ESTADO, TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO)
VALUES (-1, 'NO ESPECIFICADO', 'ND', 'NO ESPECIFICADO', 'NO ESPECIFICADO');

-- Semillas de estados observados en las fuentes (ajustables al aprobarse con CSEP, Fase 3)
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('RESOLUCION','ACTIVO','Resolución activa','VIGENTE');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('RESOLUCION','INACTIVO','Resolución inactiva','CERRADO');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('MULTA','ACTIVO','Multa activa','VIGENTE');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('MULTA','INACTIVO','Multa inactiva','CERRADO');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('MULTA','INCUMPLIDO','No pagada / incumplida','INCUMPLIDO');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('PAGO','PAGADO','Multa pagada','CUMPLIDO');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('PAGO','PENDIENTE','Pago pendiente','PENDIENTE');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('PAGO','EJECUCION_FORZOSA','En ejecución forzosa','INCUMPLIDO');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('ETAPA','TERMINADO','Etapa terminada','CUMPLIDO');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('ETAPA','PENDIENTE','Etapa pendiente','PENDIENTE');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('DESCARGOS','PRESENTO','Presentó descargos','CUMPLIDO');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('DESCARGOS','NO_PRESENTO','No presentó descargos','INCUMPLIDO');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('INFORME','EN_CUSTODIA','En custodia','VIGENTE');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('INFORME','EN_REVISION','En revisión','VIGENTE');
INSERT INTO DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('INFORME','APROBADO','Aprobado','CERRADO');

--------------------------------------------------------------------------------
-- DIM_PARAMETRO_UIT
-- Base de la regla de calidad R05 (MONTO_S = MULTA_UIT × UIT(año)). Sembrada con
-- valores oficiales del MEF; el año en curso se actualiza al publicarse el Decreto
-- Supremo correspondiente (ver hallazgo H6 en la propuesta).
--------------------------------------------------------------------------------
CREATE TABLE DIM_PARAMETRO_UIT (
    ID_UIT                NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    ANIO                  NUMBER(4)      NOT NULL,
    VALOR_UIT             NUMBER(12,2)   NOT NULL,
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DIM_PARAMETRO_UIT PRIMARY KEY (ID_UIT),
    CONSTRAINT UQ_DIM_PARAMETRO_UIT_ANIO UNIQUE (ANIO),
    CONSTRAINT CK_DIM_PARAMETRO_UIT_VALOR CHECK (VALOR_UIT > 0)
);

INSERT INTO DIM_PARAMETRO_UIT (ID_UIT, ANIO, VALOR_UIT) VALUES (-1, 0, 0); -- ND
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2015, 3850.00);
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2016, 3950.00);
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2017, 4050.00);
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2018, 4150.00);
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2019, 4200.00);
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2020, 4300.00);
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2021, 4400.00);
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2022, 4600.00);
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2023, 4950.00);
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2024, 5150.00);
INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2025, 5350.00);
-- 2026: pendiente de Decreto Supremo oficial del MEF. Actualizar cuando se publique:
-- INSERT INTO DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2026, <valor_oficial>);

COMMIT;
