--------------------------------------------------------------------------------
-- 01_dimensiones.sql
-- DWH OEFA · Oracle BD_CURSOR
-- Creación de las 8 tablas de dimensiones del modelo (ver PROPUESTA_ADAPTADA_ETL.md, sec. 3.2)
--
-- Orden de ejecución: EJECUTAR PRIMERO (los hechos referencian a estas tablas por FK).
-- Motor objetivo: Oracle 12c+ (usa GENERATED BY DEFAULT ON NULL AS IDENTITY, disponible
-- desde 12c). Si el BD_CURSOR corre en una versión anterior, reemplazar la identidad por
-- una SEQUENCE + TRIGGER equivalente.
--
-- Convención: cada dimensión trae sembrado un miembro "NO ESPECIFICADO" con clave -1,
-- para que ningún hecho se pierda por falta de dimensión (ver sección 3.2 de la propuesta).
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- DW_M_DIM_TIEMPO
-- Clave inteligente AAAAMMDD. Se puebla con un script de generación de calendario
-- (fuera del alcance de este DDL); aquí solo se crea la estructura y el miembro ND.
--------------------------------------------------------------------------------
CREATE TABLE DW_M_DIM_TIEMPO (
    ID_TIEMPO             NUMBER(8)      NOT NULL,   -- AAAAMMDD; -1 = NO ESPECIFICADO
    FECHA                 DATE,
    ANIO                  NUMBER(4),
    MES                   NUMBER(2),
    NOMBRE_MES             VARCHAR2(15),
    TRIMESTRE             NUMBER(1),
    SEMANA_ANIO           NUMBER(2),
    DIA                   NUMBER(2),
    DIA_SEMANA            VARCHAR2(10),
    NOMBRE_DIA            VARCHAR2(15),
    ES_FIN_DE_SEMANA      NUMBER(1)      DEFAULT 0,
    ES_FERIADO            NUMBER(1)      DEFAULT 0,
    ES_DIA_HABIL          NUMBER(1)      DEFAULT 1,
    DESCRIPCION_FERIADO   VARCHAR2(200),
    CONSTRAINT PK_DW_M_DIM_TIEMPO PRIMARY KEY (ID_TIEMPO),
    CONSTRAINT CK_DW_M_DIM_TIEMPO_FDS CHECK (ES_FIN_DE_SEMANA IN (0,1)),
    CONSTRAINT CK_DW_M_DIM_TIEMPO_FER CHECK (ES_FERIADO IN (0,1)),
    CONSTRAINT CK_DW_M_DIM_TIEMPO_HAB CHECK (ES_DIA_HABIL IN (0,1))
);

CREATE UNIQUE INDEX UQ_DW_M_DIM_TIEMPO_FECHA ON DW_M_DIM_TIEMPO (FECHA);

-- Miembro NO ESPECIFICADO
INSERT INTO DW_M_DIM_TIEMPO (ID_TIEMPO, FECHA, ANIO, MES, NOMBRE_MES, TRIMESTRE,
                         SEMANA_ANIO, DIA, DIA_SEMANA, NOMBRE_DIA,
                         ES_FIN_DE_SEMANA, ES_FERIADO, ES_DIA_HABIL, DESCRIPCION_FERIADO)
VALUES (-1, NULL, NULL, NULL, 'NO ESPECIFICADO', NULL,
        NULL, NULL, 'NO ESPECIFICADO', 'NO ESPECIFICADO',
        0, 0, 0, NULL);

--------------------------------------------------------------------------------
-- DW_M_DIM_ADMINISTRADO
-- Sin SCD Tipo 2: última versión vigente, actualizada por UPDATE simple.
--------------------------------------------------------------------------------
CREATE TABLE DW_M_DIM_ADMINISTRADO (
    ID_ADMINISTRADO       NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    COD_ADMINISTRADO      VARCHAR2(50)   NOT NULL,   -- ADM##### (SISUD) o NOM-<razón social>
    RAZON_SOCIAL          VARCHAR2(300),
    RAZON_SOCIAL_NORM     VARCHAR2(300),
    RUC                   VARCHAR2(20),
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DW_M_DIM_ADMINISTRADO PRIMARY KEY (ID_ADMINISTRADO),
    CONSTRAINT UQ_DW_M_DIM_ADMINISTRADO_COD UNIQUE (COD_ADMINISTRADO)
);

INSERT INTO DW_M_DIM_ADMINISTRADO (ID_ADMINISTRADO, COD_ADMINISTRADO, RAZON_SOCIAL,
                               RAZON_SOCIAL_NORM, RUC)
VALUES (-1, 'ND', 'NO ESPECIFICADO', 'NO ESPECIFICADO', NULL);

--------------------------------------------------------------------------------
-- DW_M_DIM_ORGANO_UNIDAD
-- Oficinas/coordinaciones/direcciones (ej. DSIS-CRES, DSEM-CMIN, ODES-MOQ, OD-LAM).
--------------------------------------------------------------------------------
CREATE TABLE DW_M_DIM_ORGANO_UNIDAD (
    ID_ORGANO             NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    SIGLA                 VARCHAR2(30)   NOT NULL,
    NOMBRE                VARCHAR2(200),
    DESCRIPCION           VARCHAR2(200),  -- nombre largo CSEP (ej. Minería); catálogo f2_csep_sheets.json
    TIPO                  VARCHAR2(30),   -- DIRECCION / COORDINACION / ODES / OD
    ORGANO_SUPERIOR       VARCHAR2(30),
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DW_M_DIM_ORGANO_UNIDAD PRIMARY KEY (ID_ORGANO),
    CONSTRAINT UQ_DW_M_DIM_ORGANO_SIGLA UNIQUE (SIGLA),
    CONSTRAINT CK_DW_M_DIM_ORGANO_TIPO CHECK (TIPO IN
        ('DIRECCION','COORDINACION','ODES','OD','NO ESPECIFICADO'))
);

INSERT INTO DW_M_DIM_ORGANO_UNIDAD (ID_ORGANO, SIGLA, NOMBRE, DESCRIPCION, TIPO, ORGANO_SUPERIOR)
VALUES (-1, 'ND', 'NO ESPECIFICADO', 'NO ESPECIFICADO', 'NO ESPECIFICADO', NULL);

--------------------------------------------------------------------------------
-- DW_M_DIM_OD
-- Territorio / oficina desconcentrada del Excel F1 (familia medidas administrativas).
-- Distinto de DW_M_DIM_ORGANO_UNIDAD (órgano operativo COORD/expediente).
--------------------------------------------------------------------------------
CREATE TABLE DW_M_DIM_OD (
    ID_OD                 NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    COD_OD                VARCHAR2(30)   NOT NULL,
    NOMBRE                VARCHAR2(100)  NOT NULL,
    TIPO                  VARCHAR2(20)   NOT NULL,  -- OD / ODES / UNIDAD / NO ESPECIFICADO
    ORDEN                 NUMBER(3),
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DW_M_DIM_OD PRIMARY KEY (ID_OD),
    CONSTRAINT UQ_DW_M_DIM_OD_COD UNIQUE (COD_OD),
    CONSTRAINT CK_DW_M_DIM_OD_TIPO CHECK (TIPO IN ('OD','ODES','UNIDAD','NO ESPECIFICADO'))
);

INSERT INTO DW_M_DIM_OD (ID_OD, COD_OD, NOMBRE, TIPO, ORDEN)
VALUES (-1, 'ND', 'NO ESPECIFICADO', 'NO ESPECIFICADO', NULL);

--------------------------------------------------------------------------------
-- DW_M_DIM_FUENTE_REGISTRO
-- Universo de origen de cada fila del hecho (antes dimensión degenerada VARCHAR).
-- CODIGO alinea a FUENTE_REGISTRO / constantes.py; FAMILIA_TDR = F1|F2|F4|F5.
--------------------------------------------------------------------------------
CREATE TABLE DW_M_DIM_FUENTE_REGISTRO (
    ID_FUENTE             NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    CODIGO                VARCHAR2(20)   NOT NULL,   -- OD_SHEETS / CAGR / GAPPS / SISUD_VW
    NOMBRE                VARCHAR2(100)  NOT NULL,
    FAMILIA_TDR           VARCHAR2(10),              -- F1 / F2 / F4 / F5 / ND
    DESCRIPCION           VARCHAR2(300),
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DW_M_DIM_FUENTE PRIMARY KEY (ID_FUENTE),
    CONSTRAINT UQ_DW_M_DIM_FUENTE_COD UNIQUE (CODIGO)
);

INSERT INTO DW_M_DIM_FUENTE_REGISTRO (ID_FUENTE, CODIGO, NOMBRE, FAMILIA_TDR, DESCRIPCION)
VALUES (-1, 'ND', 'NO ESPECIFICADO', 'ND', 'NO ESPECIFICADO');
INSERT INTO DW_M_DIM_FUENTE_REGISTRO (ID_FUENTE, CODIGO, NOMBRE, FAMILIA_TDR, DESCRIPCION)
VALUES (1, 'OD_SHEETS', 'Sheets OD', 'F1', '31 Google Sheets OD → STG_GS2_OD_MULTAS');
INSERT INTO DW_M_DIM_FUENTE_REGISTRO (ID_FUENTE, CODIGO, NOMBRE, FAMILIA_TDR, DESCRIPCION)
VALUES (2, 'CAGR', 'Sheets CSEP', 'F2', '10 Google Sheets CSEP → STG_GS1_CSEP_MULTAS / ETAPAS');
INSERT INTO DW_M_DIM_FUENTE_REGISTRO (ID_FUENTE, CODIGO, NOMBRE, FAMILIA_TDR, DESCRIPCION)
VALUES (3, 'GAPPS', 'MySQL GAPP (histórico)', 'F4', 'Fuera de ingestión; semilla conservada');
INSERT INTO DW_M_DIM_FUENTE_REGISTRO (ID_FUENTE, CODIGO, NOMBRE, FAMILIA_TDR, DESCRIPCION)
VALUES (4, 'SISUD_VW', 'Oracle SISUD', 'F5', 'SISUD.VW_MULTA_COERCITIVA → STG_ORA_*');
INSERT INTO DW_M_DIM_FUENTE_REGISTRO (ID_FUENTE, CODIGO, NOMBRE, FAMILIA_TDR, DESCRIPCION)
VALUES (5, 'OD_EXCEL', 'Excel OD (legacy)', 'F1', 'Alias histórico; el ETL normaliza a OD_SHEETS');

--------------------------------------------------------------------------------
-- DW_M_DIM_MATERIA_SUBSECTOR
--------------------------------------------------------------------------------
CREATE TABLE DW_M_DIM_MATERIA_SUBSECTOR (
    ID_MATERIA            NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    NOMBRE                VARCHAR2(100)  NOT NULL,
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DW_M_DIM_MATERIA PRIMARY KEY (ID_MATERIA),
    CONSTRAINT UQ_DW_M_DIM_MATERIA_NOMBRE UNIQUE (NOMBRE)
);

INSERT INTO DW_M_DIM_MATERIA_SUBSECTOR (ID_MATERIA, NOMBRE) VALUES (-1, 'NO ESPECIFICADO');
INSERT INTO DW_M_DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('HIDROCARBUROS');
INSERT INTO DW_M_DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('PESQUERIA');
INSERT INTO DW_M_DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('MINERIA');
INSERT INTO DW_M_DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('RESIDUOS SOLIDOS');
INSERT INTO DW_M_DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('INDUSTRIAS');
INSERT INTO DW_M_DIM_MATERIA_SUBSECTOR (NOMBRE) VALUES ('AGUAS');

--------------------------------------------------------------------------------
-- DW_M_DIM_ESTADO
-- Catálogo homologado de estados (resuelve el hallazgo H8: estados como texto libre
-- sin catálogo único). TIPO_ESTADO agrupa por dominio (RESOLUCION/MULTA/PAGO/ETAPA/
-- DESCARGOS); GRUPO clasifica el estado homologado.
--------------------------------------------------------------------------------
CREATE TABLE DW_M_DIM_ESTADO (
    ID_ESTADO             NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    TIPO_ESTADO           VARCHAR2(30)   NOT NULL,   -- RESOLUCION/MULTA/PAGO/ETAPA/DESCARGOS
    CODIGO                VARCHAR2(50)   NOT NULL,   -- valor homologado (ej. ACTIVO, PAGADO)
    DESCRIPCION           VARCHAR2(200),
    GRUPO                 VARCHAR2(30),   -- VIGENTE/CERRADO/CUMPLIDO/INCUMPLIDO/PENDIENTE
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DW_M_DIM_ESTADO PRIMARY KEY (ID_ESTADO),
    CONSTRAINT UQ_DW_M_DIM_ESTADO UNIQUE (TIPO_ESTADO, CODIGO)
);

INSERT INTO DW_M_DIM_ESTADO (ID_ESTADO, TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO)
VALUES (-1, 'NO ESPECIFICADO', 'ND', 'NO ESPECIFICADO', 'NO ESPECIFICADO');

-- Semillas de estados observados en las fuentes (ajustables al aprobarse con CSEP, Fase 3)
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('RESOLUCION','ACTIVO','Resolución activa','VIGENTE');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('RESOLUCION','INACTIVO','Resolución inactiva','CERRADO');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('MULTA','ACTIVO','Multa activa','VIGENTE');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('MULTA','INACTIVO','Multa inactiva','CERRADO');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('MULTA','INCUMPLIDO','No pagada / incumplida','INCUMPLIDO');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('PAGO','PAGADO','Multa pagada','CUMPLIDO');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('PAGO','PENDIENTE','Pago pendiente','PENDIENTE');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('PAGO','EJECUCION_FORZOSA','En ejecución forzosa','INCUMPLIDO');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('ETAPA','TERMINADO','Etapa terminada','CUMPLIDO');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('ETAPA','PENDIENTE','Etapa pendiente','PENDIENTE');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('DESCARGOS','PRESENTO','Presentó descargos','CUMPLIDO');
INSERT INTO DW_M_DIM_ESTADO (TIPO_ESTADO, CODIGO, DESCRIPCION, GRUPO) VALUES ('DESCARGOS','NO_PRESENTO','No presentó descargos','INCUMPLIDO');

--------------------------------------------------------------------------------
-- DW_M_DIM_PARAMETRO_UIT
-- Base de la regla de calidad R05 (MONTO_S = MULTA_UIT × UIT(año)). Sembrada con
-- valores oficiales del MEF; el año en curso se actualiza al publicarse el Decreto
-- Supremo correspondiente (ver hallazgo H6 en la propuesta).
--------------------------------------------------------------------------------
CREATE TABLE DW_M_DIM_PARAMETRO_UIT (
    ID_UIT                NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    ANIO                  NUMBER(4)      NOT NULL,
    VALOR_UIT             NUMBER(12,2)   NOT NULL,
    FECHA_ACTUALIZACION   DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_DW_M_DIM_PARAMETRO_UIT PRIMARY KEY (ID_UIT),
    CONSTRAINT UQ_DW_M_DIM_PARAMETRO_UIT_ANIO UNIQUE (ANIO),
    CONSTRAINT CK_DW_M_DIM_PARAMETRO_UIT_VALOR CHECK (VALOR_UIT > 0)
);

INSERT INTO DW_M_DIM_PARAMETRO_UIT (ID_UIT, ANIO, VALOR_UIT) VALUES (-1, 0, 0); -- ND
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2015, 3850.00);
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2016, 3950.00);
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2017, 4050.00);
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2018, 4150.00);
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2019, 4200.00);
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2020, 4300.00);
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2021, 4400.00);
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2022, 4600.00);
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2023, 4950.00);
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2024, 5150.00);
INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2025, 5350.00);
-- 2026: pendiente de Decreto Supremo oficial del MEF. Actualizar cuando se publique:
-- INSERT INTO DW_M_DIM_PARAMETRO_UIT (ANIO, VALOR_UIT) VALUES (2026, <valor_oficial>);

COMMIT;
