--------------------------------------------------------------------------------
-- 02_hechos.sql
-- DWH OEFA · Oracle BD_CURSOR
-- Creación de las tablas de hechos del modelo (ver PROPUESTA_ADAPTADA_ETL.md, sec. 3.1)
--
-- Orden de ejecución: EJECUTAR DESPUÉS de 01_dimensiones.sql (las FK dependen de que
-- existan las dimensiones y sus miembros "NO ESPECIFICADO" con clave -1).
--
-- Convención: toda FK hacia una dimensión tiene DEFAULT -1 (miembro NO ESPECIFICADO),
-- de modo que ningún hecho se pierde por falta de dimensión. El default no reemplaza
-- la responsabilidad de la capa lógica (Python) de resolver la FK correcta antes de
-- insertar; es una salvaguarda ante datos incompletos.
--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
-- MI_FACT_MULTA_COERCITIVA
-- Grano: una medida administrativa con su multa coercitiva, integrando F1+F2+F4+F5.
-- Hecho acumulativo: una sola fila recorre notificación → descargos → análisis →
-- imposición → verificación → cobranza. Las fechas de cada hito son columnas DATE
-- directas (no roles hacia MI_DIM_TIEMPO); MI_DIM_TIEMPO se usa para agrupar en consultas.
--------------------------------------------------------------------------------
CREATE TABLE MI_FACT_MULTA_COERCITIVA (
    ID_MC                     NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                               (START WITH 1 INCREMENT BY 1),

    -- Identificadores / dimensiones degeneradas (conservan la clave natural de origen)
    COD_MA                    VARCHAR2(50),
    COD_PROY_MC               VARCHAR2(100),
    NUMERO_EXPEDIENTE         VARCHAR2(50),
    EXP_RES_MC                VARCHAR2(50),
    N_RES_MC                  VARCHAR2(50),
    CUM                       VARCHAR2(20),
    CAM                       VARCHAR2(20),
    NUMERO_REGISTRO_SIGED     VARCHAR2(50),

    -- Vínculo con el hecho de supervisión (drill-across), cuando existe amarre por expediente
    ID_INFORME                NUMBER,

    -- FKs de dimensión (DEFAULT -1 = NO ESPECIFICADO)
    ID_ADMINISTRADO           NUMBER          DEFAULT -1  NOT NULL,
    ID_ORGANO                 NUMBER          DEFAULT -1  NOT NULL,
    ID_MATERIA                NUMBER          DEFAULT -1  NOT NULL,
    ID_ESTADO_RESOLUCION      NUMBER          DEFAULT -1  NOT NULL,
    ID_ESTADO_MULTA           NUMBER          DEFAULT -1  NOT NULL,
    ID_ESTADO_PAGO            NUMBER          DEFAULT -1  NOT NULL,
    ID_UIT                    NUMBER          DEFAULT -1  NOT NULL,

    -- Fechas del ciclo de vida (columnas DATE directas)
    F_NOTIF_DCG               DATE,   -- notificación de la carta de descargos
    F_VENC_DCG                DATE,   -- vencimiento para presentar descargos
    F_RPTA_ADM                DATE,   -- respuesta del administrado
    F_INIC_ANALISIS           DATE,
    F_FIN_ANALISIS            DATE,
    F_FIRMA_RES_MC            DATE,   -- firma de la resolución de multa
    F_NOTIF_RES_MC            DATE,   -- notificación de la resolución
    F_VENC_MC                 DATE,   -- vencimiento de la multa
    F_VERIF_POST_MC           DATE,   -- verificación posterior
    F_PAGO                    DATE,
    F_REMISION_MEMO           DATE,   -- remisión del memo de ejecución forzosa

    -- Atributos descriptivos
    PRESENTO_DESCARGOS        CHAR(1),        -- 'S' / 'N'
    AMERITA_MC                CHAR(1),        -- 'S' / 'N'
    REQUIERE_VERIF_CAMPO      CHAR(1),        -- 'S' / 'N'
    MEDIDA_ADMINISTRATIVA     VARCHAR2(1000),
    MEMO_EF                   VARCHAR2(50),
    SIGED                     VARCHAR2(50),
    DOC_VERIF_MC              VARCHAR2(100),

    -- Medidas aditivas (montos)
    MONTO_UIT                 NUMBER(10,4),
    VALOR_UIT_APLICADO        NUMBER(12,2),
    MONTO_S                   NUMBER(14,2),   -- reportado por la fuente
    MONTO_S_CALC              NUMBER(14,2),   -- recalculado: MONTO_UIT * VALOR_UIT_APLICADO
    MONTO_MULTA_REC           NUMBER(14,2),
    MONTO_MULTA_TFA           NUMBER(14,2),

    -- Medidas de tiempo (días, calculadas por la capa lógica)
    DIAS_NOTIF_A_RESPUESTA    NUMBER(6),
    DIAS_ANALISIS             NUMBER(6),
    DIAS_NOTIF_A_FIRMA        NUMBER(6),
    DIAS_FIRMA_A_VENC         NUMBER(6),
    DIAS_VENC_A_PAGO          NUMBER(6),
    DIAS_RESOL_A_VERIF        NUMBER(6),

    -- Flags semiaditivos
    FLAG_PRESENTO_DCG         NUMBER(1)       DEFAULT 0,
    FLAG_AMERITA_MC           NUMBER(1)       DEFAULT 0,
    FLAG_PAGADA               NUMBER(1)       DEFAULT 0,
    FLAG_EJECUCION_FORZOSA    NUMBER(1)       DEFAULT 0,
    FLAG_CUMPLIO_VERIF        NUMBER(1)       DEFAULT 0,

    -- Linaje
    FUENTE_REGISTRO           VARCHAR2(20)    NOT NULL,   -- LAM_OD / CAGR / GAPPS / SISUD_VW
    FECHA_CARGA               DATE            DEFAULT SYSDATE,

    CONSTRAINT PK_FACT_MC PRIMARY KEY (ID_MC),
    CONSTRAINT FK_FMC_ADMINISTRADO FOREIGN KEY (ID_ADMINISTRADO) REFERENCES MI_DIM_ADMINISTRADO (ID_ADMINISTRADO),
    CONSTRAINT FK_FMC_ORGANO       FOREIGN KEY (ID_ORGANO)       REFERENCES MI_DIM_ORGANO_UNIDAD (ID_ORGANO),
    CONSTRAINT FK_FMC_MATERIA      FOREIGN KEY (ID_MATERIA)      REFERENCES MI_DIM_MATERIA_SUBSECTOR (ID_MATERIA),
    CONSTRAINT FK_FMC_EST_RESOL    FOREIGN KEY (ID_ESTADO_RESOLUCION) REFERENCES MI_DIM_ESTADO (ID_ESTADO),
    CONSTRAINT FK_FMC_EST_MULTA    FOREIGN KEY (ID_ESTADO_MULTA)      REFERENCES MI_DIM_ESTADO (ID_ESTADO),
    CONSTRAINT FK_FMC_EST_PAGO     FOREIGN KEY (ID_ESTADO_PAGO)       REFERENCES MI_DIM_ESTADO (ID_ESTADO),
    CONSTRAINT FK_FMC_UIT          FOREIGN KEY (ID_UIT)          REFERENCES MI_DIM_PARAMETRO_UIT (ID_UIT),
    CONSTRAINT CK_FMC_PRESENTO_DCG CHECK (PRESENTO_DESCARGOS IN ('S','N') OR PRESENTO_DESCARGOS IS NULL),
    CONSTRAINT CK_FMC_AMERITA_MC   CHECK (AMERITA_MC IN ('S','N') OR AMERITA_MC IS NULL),
    CONSTRAINT CK_FMC_REQ_VERIF    CHECK (REQUIERE_VERIF_CAMPO IN ('S','N') OR REQUIERE_VERIF_CAMPO IS NULL),
    CONSTRAINT CK_FMC_FLAG_DCG     CHECK (FLAG_PRESENTO_DCG IN (0,1)),
    CONSTRAINT CK_FMC_FLAG_AMER    CHECK (FLAG_AMERITA_MC IN (0,1)),
    CONSTRAINT CK_FMC_FLAG_PAG     CHECK (FLAG_PAGADA IN (0,1)),
    CONSTRAINT CK_FMC_FLAG_EF      CHECK (FLAG_EJECUCION_FORZOSA IN (0,1)),
    CONSTRAINT CK_FMC_FLAG_VERIF   CHECK (FLAG_CUMPLIO_VERIF IN (0,1)),
    CONSTRAINT CK_FMC_FUENTE       CHECK (FUENTE_REGISTRO IN ('LAM_OD','CAGR','GAPPS','SISUD_VW'))
);

CREATE INDEX IX_FMC_CUM_CAM   ON MI_FACT_MULTA_COERCITIVA (CUM, CAM);
CREATE INDEX IX_FMC_EXPEDIENTE ON MI_FACT_MULTA_COERCITIVA (NUMERO_EXPEDIENTE);
CREATE INDEX IX_FMC_ADMIN     ON MI_FACT_MULTA_COERCITIVA (ID_ADMINISTRADO);
CREATE INDEX IX_FMC_ORGANO    ON MI_FACT_MULTA_COERCITIVA (ID_ORGANO);
CREATE INDEX IX_FMC_INFORME   ON MI_FACT_MULTA_COERCITIVA (ID_INFORME);

--------------------------------------------------------------------------------
-- MI_FACT_INFORME_SUPERVISION
-- Grano: un informe de supervisión (fila de F3, CSEP_INFORMES_VIEW).
--------------------------------------------------------------------------------
CREATE TABLE MI_FACT_INFORME_SUPERVISION (
    ID_INFORME                NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                               (START WITH 1 INCREMENT BY 1),

    -- Degeneradas
    IDACTIVIDAD               NUMBER,
    TXCUC                     VARCHAR2(50),
    TXNUMEXP                  VARCHAR2(50),
    TXINFORME                 VARCHAR2(100),

    -- FKs de dimensión
    ID_ADMINISTRADO           NUMBER          DEFAULT -1  NOT NULL,
    ID_ORGANO                 NUMBER          DEFAULT -1  NOT NULL,
    ID_MATERIA                NUMBER          DEFAULT -1  NOT NULL,
    ID_ESTADO_INFORME         NUMBER          DEFAULT -1  NOT NULL,

    -- Atributos
    TIPO_SUPERVISION          VARCHAR2(20),   -- ESPECIAL / REGULAR
    FUENTE_PROGRAMACION       VARCHAR2(20),   -- PLANEFA / OTRA
    NIVEL_REVISION            VARCHAR2(200),

    -- Fechas del ciclo del informe
    F_INICIO                  DATE,
    F_FIN                     DATE,
    F_INFORME_ESPERADO        DATE,
    F_INFORME                 DATE,
    F_REG_INFORME             DATE,

    -- Medidas calculadas
    DIAS_SUPERVISION          NUMBER(6),      -- F_FIN - F_INICIO
    DIAS_ELAB_INFORME         NUMBER(6),      -- F_INFORME - F_FIN
    FLAG_INFORME_OPORTUNO     NUMBER(1)       DEFAULT 0,  -- F_INFORME <= F_INFORME_ESPERADO
    FLAG_DERIVADO             NUMBER(1)       DEFAULT 0,

    -- Linaje
    FUENTE_REGISTRO           VARCHAR2(20)    DEFAULT 'SISUD_INF' NOT NULL,
    FECHA_CARGA               DATE            DEFAULT SYSDATE,

    CONSTRAINT PK_FACT_INFORME PRIMARY KEY (ID_INFORME),
    CONSTRAINT FK_FINF_ADMINISTRADO FOREIGN KEY (ID_ADMINISTRADO) REFERENCES MI_DIM_ADMINISTRADO (ID_ADMINISTRADO),
    CONSTRAINT FK_FINF_ORGANO       FOREIGN KEY (ID_ORGANO)       REFERENCES MI_DIM_ORGANO_UNIDAD (ID_ORGANO),
    CONSTRAINT FK_FINF_MATERIA      FOREIGN KEY (ID_MATERIA)      REFERENCES MI_DIM_MATERIA_SUBSECTOR (ID_MATERIA),
    CONSTRAINT FK_FINF_ESTADO       FOREIGN KEY (ID_ESTADO_INFORME) REFERENCES MI_DIM_ESTADO (ID_ESTADO),
    CONSTRAINT CK_FINF_OPORTUNO     CHECK (FLAG_INFORME_OPORTUNO IN (0,1)),
    CONSTRAINT CK_FINF_DERIVADO     CHECK (FLAG_DERIVADO IN (0,1))
);

CREATE INDEX IX_FINF_TXCUC    ON MI_FACT_INFORME_SUPERVISION (TXCUC);
CREATE INDEX IX_FINF_TXNUMEXP ON MI_FACT_INFORME_SUPERVISION (TXNUMEXP);
CREATE INDEX IX_FINF_ADMIN    ON MI_FACT_INFORME_SUPERVISION (ID_ADMINISTRADO);
CREATE INDEX IX_FINF_ORGANO   ON MI_FACT_INFORME_SUPERVISION (ID_ORGANO);

-- FK diferida de MI_FACT_MULTA_COERCITIVA -> MI_FACT_INFORME_SUPERVISION (drill-across),
-- se agrega aquí porque ambas tablas deben existir primero.
ALTER TABLE MI_FACT_MULTA_COERCITIVA
    ADD CONSTRAINT FK_FMC_INFORME FOREIGN KEY (ID_INFORME)
    REFERENCES MI_FACT_INFORME_SUPERVISION (ID_INFORME);

--------------------------------------------------------------------------------
-- MI_DET_ETAPA_MC
-- Tabla de detalle (no es un tercer hecho dimensional): una etapa del flujo de
-- elaboración de la multa (hoja "2) Etapas" de F2 / CAGR). Información operativa
-- de apoyo, enlazada al hecho padre por COD_PROY_MC / ID_MC.
--------------------------------------------------------------------------------
CREATE TABLE MI_DET_ETAPA_MC (
    ID_ETAPA_MC               NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                               (START WITH 1 INCREMENT BY 1),
    ID_MC                     NUMBER,         -- FK al hecho padre, nulable (puede no amarrar aún)
    COD_PROY_MC               VARCHAR2(100)   NOT NULL,
    NRO_ETAPA                 NUMBER(3),
    ACCION                    VARCHAR2(100),  -- ELABORACION / REVISION / CALCULO / FIRMA
    PERFIL_ENCARGADO          VARCHAR2(100),
    ENCARGADO                 VARCHAR2(150),
    F_ASIGNACION              DATE,
    F_ENTREGA_DEV             DATE,
    ESTADO_ETAPA              VARCHAR2(30),   -- TERMINADO / PENDIENTE
    CONFORMIDAD               VARCHAR2(50),
    DIAS_ELABORACION          NUMBER(6),      -- días hábiles (calculado con MI_DIM_TIEMPO)
    FUENTE_REGISTRO           VARCHAR2(20)    DEFAULT 'CAGR' NOT NULL,
    FECHA_CARGA               DATE            DEFAULT SYSDATE,

    CONSTRAINT PK_MI_DET_ETAPA_MC PRIMARY KEY (ID_ETAPA_MC),
    CONSTRAINT FK_DETAPA_FACT_MC FOREIGN KEY (ID_MC) REFERENCES MI_FACT_MULTA_COERCITIVA (ID_MC)
);

CREATE INDEX IX_DETAPA_COD_PROY ON MI_DET_ETAPA_MC (COD_PROY_MC);
CREATE INDEX IX_DETAPA_ID_MC    ON MI_DET_ETAPA_MC (ID_MC);

COMMIT;
