--------------------------------------------------------------------------------
-- 03_bitacora.sql
-- DWH OEFA · Oracle BD_CURSOR
-- Tabla de bitácora de calidad de datos (ver PROPUESTA_ADAPTADA_ETL.md, sec. 3.3 y 4)
--
-- Orden de ejecución: EJECUTAR AL FINAL (después de 01_dimensiones.sql y
-- 02_hechos.sql). No tiene FK hacia las dimensiones/hechos a propósito: debe poder
-- registrar hallazgos incluso sobre filas que fueron rechazadas y nunca llegaron a
-- insertarse como hecho (por eso REGISTRO_ID es un identificador de texto libre,
-- no una FK dura).
--------------------------------------------------------------------------------

CREATE TABLE DQ_HALLAZGO (
    ID_HALLAZGO           NUMBER          GENERATED BY DEFAULT ON NULL AS IDENTITY
                                           (START WITH 1 INCREMENT BY 1),

    -- Identificación del lote de carga (coincide con el run de Apache Hop)
    ID_CARGA              VARCHAR2(50)    NOT NULL,
    FECHA_CARGA           DATE            DEFAULT SYSDATE NOT NULL,

    -- Regla de calidad que generó el hallazgo (ver sección 4 de la propuesta)
    REGLA_CODIGO          VARCHAR2(10)    NOT NULL,   -- R01..R05
    REGLA_DESCRIPCION     VARCHAR2(200),

    -- Ubicación del hallazgo
    FUENTE_ORIGEN         VARCHAR2(20)    NOT NULL,   -- F1..F5 / LAM_OD / CAGR / GAPPS / SISUD_VW / SISUD_INF
    TABLA_DESTINO         VARCHAR2(50),               -- tabla en BD_CURSOR afectada, si aplica
    REGISTRO_ID           VARCHAR2(200),              -- clave natural de la fila afectada (COD_MA, CUM+CAM, expediente, etc.)
    CAMPO                 VARCHAR2(100),
    VALOR_ENCONTRADO      VARCHAR2(500),

    -- Severidad y ciclo de vida del hallazgo
    SEVERIDAD             VARCHAR2(20)    NOT NULL,   -- CRITICA / ADVERTENCIA
    ESTADO                VARCHAR2(20)    DEFAULT 'PENDIENTE' NOT NULL,  -- PENDIENTE / CORREGIDO / ACEPTADO
    OBSERVACION           VARCHAR2(500),
    FECHA_RESOLUCION       DATE,
    RESUELTO_POR          VARCHAR2(100),  -- usuario/área que corrigió o aceptó (ej. CSEP)

    CONSTRAINT PK_DQ_HALLAZGO PRIMARY KEY (ID_HALLAZGO),
    CONSTRAINT CK_DQ_REGLA CHECK (REGLA_CODIGO IN ('R01','R02','R03','R04','R05')),
    CONSTRAINT CK_DQ_SEVERIDAD CHECK (SEVERIDAD IN ('CRITICA','ADVERTENCIA')),
    CONSTRAINT CK_DQ_ESTADO CHECK (ESTADO IN ('PENDIENTE','CORREGIDO','ACEPTADO'))
);

CREATE INDEX IX_DQ_ID_CARGA   ON DQ_HALLAZGO (ID_CARGA);
CREATE INDEX IX_DQ_REGLA      ON DQ_HALLAZGO (REGLA_CODIGO);
CREATE INDEX IX_DQ_ESTADO     ON DQ_HALLAZGO (ESTADO);
CREATE INDEX IX_DQ_FUENTE     ON DQ_HALLAZGO (FUENTE_ORIGEN);

-- Referencia de las 5 reglas de calidad para documentar REGLA_CODIGO (no es una tabla
-- de catálogo obligatoria del modelo; se deja como comentario de referencia rápida):
--   R01 · Completitud de campos clave (código de medida, expediente, CUM/CAM)
--   R02 · Formato válido de CUM/CAM
--   R03 · Coherencia temporal (fecha de vencimiento >= fecha de notificación, etc.)
--   R04 · Montos UIT >= 0
--   R05 · Coherencia UIT<->soles (MONTO_S = MULTA_UIT x UIT del año de la resolución)

COMMIT;
