--------------------------------------------------------------------------------
-- 04_indicadores.sql
-- DWH OEFA · Oracle BD_CURSOR
-- Indicadores K1–K5 (PROPUESTA_ADAPTADA_ETL.md secc. 5 y Fase 7)
--
-- Orden de ejecución: EJECUTAR DESPUÉS de 01, 02 y 03.
-- Sin FK hacia hechos/dimensiones: agregados de corrida, full refresh por ID_CARGA.
--------------------------------------------------------------------------------

CREATE TABLE MI_INDICADOR_RESULTADO (
    ID_RESULTADO       NUMBER         GENERATED BY DEFAULT ON NULL AS IDENTITY
                                          (START WITH 1 INCREMENT BY 1),
    ID_CARGA           VARCHAR2(20)   NOT NULL,
    FECHA_CARGA        DATE           DEFAULT SYSDATE,
    COD_INDICADOR      VARCHAR2(5)    NOT NULL,   -- K1 .. K5
    NOMBRE_INDICADOR   VARCHAR2(200),
    ANIO               NUMBER(4),
    ID_ORGANO          NUMBER         DEFAULT -1,
    ID_MATERIA         NUMBER         DEFAULT -1,
    METRICA            VARCHAR2(50)   NOT NULL,
    SUBGRANO           VARCHAR2(100),            -- REGLA, PUENTE, SOLES/UIT
    NUMERADOR          NUMBER(18,4),
    DENOMINADOR        NUMBER(18,4),
    VALOR              NUMBER(18,4),
    UNIDAD             VARCHAR2(20),
    CONSTRAINT PK_MI_INDICADOR_RESULTADO PRIMARY KEY (ID_RESULTADO)
);

CREATE INDEX IX_IND_COD ON MI_INDICADOR_RESULTADO (COD_INDICADOR);
CREATE INDEX IX_IND_CARGA ON MI_INDICADOR_RESULTADO (ID_CARGA);
CREATE INDEX IX_IND_ANIO_ORG ON MI_INDICADOR_RESULTADO (ANIO, ID_ORGANO);
