"""Capa STG: columnas introspectadas -> CREATE TABLE H2 + apply JDBC.

No extrae filas. La conexión JDBC vive en h2_conn (compartida).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from h2_conn import connect_h2 as _connect_h2

IDENT_RE = re.compile(r"[^A-Za-z0-9_]")

VARCHAR_SRC = {
    "VARCHAR2", "NVARCHAR2", "VARCHAR", "NVARCHAR", "CHAR", "NCHAR",
    "CLOB", "NCLOB", "LONG", "RAW", "BLOB", "TEXT", "TINYTEXT",
    "MEDIUMTEXT", "LONGTEXT", "JSON", "ENUM", "SET", "XMLTYPE",
}
INT_SRC = {
    "INT", "INTEGER", "BIGINT", "SMALLINT", "TINYINT", "MEDIUMINT",
    "BINARY_INTEGER", "PLS_INTEGER",
}
DEC_SRC = {
    "FLOAT", "BINARY_FLOAT", "BINARY_DOUBLE", "DOUBLE", "REAL",
}
TS_SRC = {"TIMESTAMP", "DATETIME", "TIMESTAMPTZ", "TIMESTAMP WITH TIME ZONE"}
DATE_SRC = {"DATE"}
BOOL_SRC = {"BOOLEAN", "BOOL", "BIT"}


@dataclass(frozen=True)
class Column:
    name: str
    h2_type: str


def sanitize_ident(name: str, used: set[str] | None = None) -> str:
    raw = "" if name is None else str(name).strip()
    s = IDENT_RE.sub("_", raw)
    s = re.sub(r"_+", "_", s).strip("_")
    if not s:
        s = "COL"
    if s[0].isdigit():
        s = "C_" + s
    s = s.upper()
    if used is None:
        return s
    base = s
    n = 2
    while s in used:
        s = f"{base}_{n}"
        n += 1
    used.add(s)
    return s


def map_h2_type(
    data_type: str,
    *,
    scale: int | None = None,
    sheets: bool = False,
) -> str:
    if sheets:
        return "VARCHAR"
    dt = (data_type or "").upper().split("(")[0].strip()
    if dt in VARCHAR_SRC:
        return "VARCHAR"
    if dt in BOOL_SRC:
        return "VARCHAR"
    if dt in TS_SRC:
        return "TIMESTAMP"
    if dt in DATE_SRC:
        return "TIMESTAMP"
    if dt in INT_SRC:
        return "BIGINT"
    if dt in {"NUMBER", "DECIMAL", "NUMERIC"}:
        if scale is None or int(scale) == 0:
            return "BIGINT"
        return "DECIMAL"
    if dt in DEC_SRC:
        return "DECIMAL"
    return "VARCHAR"


def create_table_sql(stg_table: str, columns: list[Column]) -> str:
    table = sanitize_ident(stg_table)
    if not columns:
        raise ValueError(f"{table}: introspección sin columnas")
    lines = [f'    "{col.name}" {col.h2_type}' for col in columns]
    body = ",\n".join(lines)
    return f"CREATE TABLE IF NOT EXISTS {table} (\n{body}\n);"


def render_script(statements: list[tuple[str, str]]) -> str:
    chunks = [
        "-- GENERATED by python/create_stg.py — no editar",
        "-- Regenera cada corrida desde inputs.yaml. Reset H2 NO ejecuta este archivo.",
        "",
    ]
    if not statements:
        chunks.append("-- sources: []  (no-op)")
        chunks.append("")
        return "\n".join(chunks)
    for stg, sql in statements:
        chunks.append(f"-- {stg}")
        chunks.append(sql)
        chunks.append("")
    return "\n".join(chunks)


def write_script(root: Path, statements: list[tuple[str, str]]) -> Path:
    out = root / "h2" / "sql" / "02_stg.sql"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_script(statements), encoding="utf-8")
    return out


def apply_h2(root: Path, variables: dict[str, str], statements: list[tuple[str, str]]) -> None:
    if not statements:
        return
    conn = _connect_h2(root, variables)
    try:
        cur = conn.cursor()
        try:
            for stg, sql in statements:
                cur.execute(sql)
                print(f"H2 CREATE {stg}")
        finally:
            cur.close()
        conn.commit()
    finally:
        conn.close()
